/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.gotrafyinventory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author luisa
 */
public class Category extends javax.swing.JInternalFrame {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        updateCatTable();
    }

    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        jSeparator51 = new javax.swing.JSeparator();
        catId = new javax.swing.JTextField();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        catTable = new javax.swing.JTable();
        catAddBtn = new javax.swing.JButton();
        catDeleteBtn = new javax.swing.JButton();
        jSeparator52 = new javax.swing.JSeparator();
        catEditBtn = new javax.swing.JButton();
        catName = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 0), new java.awt.Dimension(150, 0), new java.awt.Dimension(150, 32767));

        setBorder(null);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setForeground(new java.awt.Color(121, 172, 131));
        jPanel26.setPreferredSize(new java.awt.Dimension(735, 450));

        jLabel123.setBackground(new java.awt.Color(110, 174, 133));
        jLabel123.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(110, 174, 133));
        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel123.setText("CATEGORIAS DE PRODUCTOS");

        jSeparator51.setBackground(new java.awt.Color(110, 174, 133));
        jSeparator51.setForeground(new java.awt.Color(110, 174, 133));

        catId.setBackground(new java.awt.Color(255, 255, 255));
        catId.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        catId.setForeground(new java.awt.Color(51, 51, 51));

        jLabel124.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(0, 0, 0));
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel124.setText("ID:");
        jLabel124.setToolTipText("");
        jLabel124.setFocusable(false);
        jLabel124.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel125.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(0, 0, 0));
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel125.setText("Nombre:");
        jLabel125.setToolTipText("");
        jLabel125.setFocusable(false);
        jLabel125.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        catTable.setBackground(new java.awt.Color(255, 255, 255));
        catTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        catTable.setForeground(new java.awt.Color(51, 51, 51));
        catTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catTable.setSelectionBackground(new java.awt.Color(110, 174, 133));
        catTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        catTable.getTableHeader().setResizingAllowed(false);
        catTable.getTableHeader().setReorderingAllowed(false);
        catTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catTableMouseClicked(evt);
            }
        });
        jScrollPane26.setViewportView(catTable);

        catAddBtn.setBackground(new java.awt.Color(204, 204, 204));
        catAddBtn.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        catAddBtn.setForeground(new java.awt.Color(102, 102, 102));
        catAddBtn.setText("Agregar");
        catAddBtn.setBorder(null);
        catAddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catAddBtnMouseClicked(evt);
            }
        });

        catDeleteBtn.setBackground(new java.awt.Color(255, 153, 153));
        catDeleteBtn.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        catDeleteBtn.setForeground(new java.awt.Color(102, 102, 102));
        catDeleteBtn.setText("Eliminar");
        catDeleteBtn.setBorder(null);
        catDeleteBtn.setMaximumSize(new java.awt.Dimension(51, 26));
        catDeleteBtn.setMinimumSize(new java.awt.Dimension(51, 26));
        catDeleteBtn.setPreferredSize(new java.awt.Dimension(51, 26));
        catDeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catDeleteBtnMouseClicked(evt);
            }
        });

        jSeparator52.setForeground(new java.awt.Color(110, 174, 133));

        catEditBtn.setBackground(new java.awt.Color(204, 204, 204));
        catEditBtn.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        catEditBtn.setForeground(new java.awt.Color(102, 102, 102));
        catEditBtn.setText("Editar");
        catEditBtn.setBorder(null);
        catEditBtn.setPreferredSize(new java.awt.Dimension(36, 26));
        catEditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catEditBtnMouseClicked(evt);
            }
        });

        catName.setBackground(new java.awt.Color(255, 255, 255));
        catName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        catName.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator51)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel124, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel125, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(catId)
                                    .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                                .addComponent(catEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(catDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(catAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator52)
                            .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel123)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator51, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel124)
                            .addComponent(catId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel125)
                            .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(catAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(catEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(catDeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void updateCatTable()
    {
        String url = "jdbc:mysql://localhost:3306/trafy_inventory";
        String user = "root";
        String ps = "hola123";
        try {
            Con = DriverManager.getConnection(url, user, ps);
            St = Con.createStatement();
            Rs = St.executeQuery("select * from category");
            catTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch(SQLException ex) {
            ex.printStackTrace();
        }
    }
    //AGREGAR
    private void catAddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catAddBtnMouseClicked
        String url = "jdbc:mysql://localhost:3306/trafy_inventory";
        String user = "root";
        String ps = "hola123";
        
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Con = DriverManager.getConnection(url, user, ps);
            System.out.print("Conexion exitosa");

            //Con = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB","Luis","Cocoroloco22");
            String sql = "Insert into category (id, name)" + "values (?, ?)";
            PreparedStatement add = Con.prepareStatement(sql);
            add.setInt(1, Integer.valueOf(catId.getText()));
            add.setString(2,catName.getText());
            //int row =add.executeUpdate();
            add.execute();
            Con.close();
            JOptionPane.showMessageDialog(this, "Categoria añadida correctamente");
            updateCatTable();
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_catAddBtnMouseClicked

    // ELIMINAR
    private void catDeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catDeleteBtnMouseClicked
        if(catId.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Seleccione una categoria");
        else
        {
            String url = "jdbc:mysql://localhost:3306/trafy_inventory";
            String user = "root";
            String ps = "hola123";
            try {
                Con = DriverManager.getConnection(url, user, ps);
                Statement Add = Con.createStatement();
                Rs = Add.executeQuery("select * from category where id="+catId.getText());
                if(Rs.next())
                {
                    Add.executeUpdate("Delete from category where id="+catId.getText());
                    updateCatTable(); 
                    JOptionPane.showMessageDialog(this, "Categoria eliminada correctamente");
                }
                else
                    JOptionPane.showMessageDialog(this, "ID de la categoria no encontrado");
            } catch(SQLException ex) {
                ex.printStackTrace();
            } 
        }
    }//GEN-LAST:event_catDeleteBtnMouseClicked

    //EDITAR
    private void catEditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catEditBtnMouseClicked
        if(catId.getText().isEmpty() || catName.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Falta Información");
        else
        {
            String url = "jdbc:mysql://localhost:3306/trafy_inventory";
            String user = "root";
            String ps = "hola123";
            try {
                Con = DriverManager.getConnection(url, user, ps);
                Statement Add = Con.createStatement();
                Rs = Add.executeQuery("select * from category where id="+catId.getText());
                if(Rs.next())
                {
                    Add.executeUpdate("update category set NAME='"+catName.getText()+"' where ID="+catId.getText());
                    updateCatTable(); 
                    JOptionPane.showMessageDialog(this, "Categoria modificado correctamente");
                }
                else
                    JOptionPane.showMessageDialog(this, "ID de la categoria no encontrado.\nEl ID no puede ser modificado."); 
            } catch(SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_catEditBtnMouseClicked

    //SELECCIONAR
    private void catTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catTableMouseClicked
        DefaultTableModel model =  (DefaultTableModel) catTable.getModel();
        int row = catTable.getSelectedRow();
        catId.setText(model.getValueAt (row, 0).toString());
        catName.setText(model.getValueAt (row, 1).toString());
    }//GEN-LAST:event_catTableMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton catAddBtn;
    private javax.swing.JButton catDeleteBtn;
    private javax.swing.JButton catEditBtn;
    private javax.swing.JTextField catId;
    private javax.swing.JTextField catName;
    private javax.swing.JTable catTable;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    // End of variables declaration//GEN-END:variables
}
