/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.gotrafyinventory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author luisa
 */
public class Category extends javax.swing.JInternalFrame {

    /**
     * Creates new form Product
     */
    public Category() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        jSeparator51 = new javax.swing.JSeparator();
        catId = new javax.swing.JTextField();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        products5 = new javax.swing.JTable();
        addBtn5 = new javax.swing.JButton();
        deleteBtn5 = new javax.swing.JButton();
        jSeparator52 = new javax.swing.JSeparator();
        editBtn5 = new javax.swing.JButton();
        catName = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 0), new java.awt.Dimension(150, 0), new java.awt.Dimension(150, 32767));

        setBorder(null);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setForeground(new java.awt.Color(121, 172, 131));
        jPanel26.setPreferredSize(new java.awt.Dimension(735, 450));

        jLabel123.setBackground(new java.awt.Color(110, 174, 133));
        jLabel123.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(110, 174, 133));
        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel123.setText("CATEGORIAS DE PRODUCTOS");

        jSeparator51.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator51.setForeground(new java.awt.Color(110, 174, 133));

        catId.setBackground(new java.awt.Color(255, 255, 255));
        catId.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        catId.setForeground(new java.awt.Color(51, 51, 51));

        jLabel124.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(0, 0, 0));
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel124.setText("ID:");
        jLabel124.setToolTipText("");
        jLabel124.setFocusable(false);
        jLabel124.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel125.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(0, 0, 0));
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel125.setText("Nombre:");
        jLabel125.setToolTipText("");
        jLabel125.setFocusable(false);
        jLabel125.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        products5.setBackground(new java.awt.Color(255, 255, 255));
        products5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        products5.setForeground(new java.awt.Color(51, 51, 51));
        products5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE"
            }
        ));
        products5.setSelectionBackground(new java.awt.Color(110, 174, 133));
        products5.setSelectionForeground(new java.awt.Color(255, 255, 255));
        products5.getTableHeader().setResizingAllowed(false);
        products5.getTableHeader().setReorderingAllowed(false);
        jScrollPane26.setViewportView(products5);

        addBtn5.setBackground(new java.awt.Color(204, 204, 204));
        addBtn5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        addBtn5.setForeground(new java.awt.Color(102, 102, 102));
        addBtn5.setText("Agregar");
        addBtn5.setBorder(null);
        addBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtn5MouseClicked(evt);
            }
        });
        addBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn5ActionPerformed(evt);
            }
        });

        deleteBtn5.setBackground(new java.awt.Color(255, 153, 153));
        deleteBtn5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        deleteBtn5.setForeground(new java.awt.Color(102, 102, 102));
        deleteBtn5.setText("Eliminar");
        deleteBtn5.setBorder(null);
        deleteBtn5.setMaximumSize(new java.awt.Dimension(51, 26));
        deleteBtn5.setMinimumSize(new java.awt.Dimension(51, 26));
        deleteBtn5.setPreferredSize(new java.awt.Dimension(51, 26));
        deleteBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn5ActionPerformed(evt);
            }
        });

        jSeparator52.setForeground(new java.awt.Color(110, 174, 133));

        editBtn5.setBackground(new java.awt.Color(204, 204, 204));
        editBtn5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        editBtn5.setForeground(new java.awt.Color(102, 102, 102));
        editBtn5.setText("Editar");
        editBtn5.setBorder(null);
        editBtn5.setPreferredSize(new java.awt.Dimension(36, 26));
        editBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn5ActionPerformed(evt);
            }
        });

        catName.setBackground(new java.awt.Color(255, 255, 255));
        catName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        catName.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator51)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel124, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel125, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(catId)
                                    .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                                .addComponent(editBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator52, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel123)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator51, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel124)
                            .addComponent(catId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel125)
                            .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(deleteBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtn5MouseClicked
        String url = "jdbc:mysql://localhost:3306/trafy_inventory";
        String user = "root";
        String ps = "cOCOROLOCO22";
        
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Con = DriverManager.getConnection(url, user, ps);
            System.out.print("Coneccion exitosa");

            //Con = DriverManager.getConnection("jdbc:derby://localhost:1527/InventoryDB","Luis","Cocoroloco22");
            String sql = "Insert into category (id, name)" + "values (?, ?)";
            PreparedStatement add = Con.prepareStatement(sql);
            add.setInt(1, Integer.valueOf(catId.getText()));
            add.setString(2,catName.getText());
            //int row =add.executeUpdate();
            add.execute();
            Con.close();
            JOptionPane.showMessageDialog(this, "Producto añadido correctamente");

        } catch (SQLException ex) {
            ex.printStackTrace();
            //Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
            //Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBtn5MouseClicked

    private void addBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtn5ActionPerformed

    private void deleteBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtn5ActionPerformed

    private void editBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtn5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn5;
    private javax.swing.JTextField catId;
    private javax.swing.JTextField catName;
    private javax.swing.JButton deleteBtn5;
    private javax.swing.JButton editBtn5;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JTable products5;
    // End of variables declaration//GEN-END:variables
}
